services:
  - type: web
    name: hustlerlink-web
    env: node
    buildCommand: "./build.sh"
    startCommand: "php -S 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hustlerlink-db
          property: connectionString
